/**
 * Gallery id → project file shown in Copy / Code when a real component exists.
 */
export const sourceFileById: Record<string, string> = {
  conversation: "src/components/naisu/conversation.tsx",
  message: "src/components/naisu/message.tsx",
  "message-single": "src/components/naisu/message.tsx",
  "message-group": "src/components/naisu/message.tsx",
  "prompt-input": "src/components/naisu/prompt-input.tsx",
  markdown: "src/components/naisu/markdown.tsx",
  "code-block": "src/components/naisu/code-block.tsx",
  attachment: "src/components/naisu/attachment.tsx",
  "tool-call": "src/components/naisu/tool-call.tsx",
  "tool-call-single": "src/components/naisu/tool-call.tsx",
  "tool-call-group": "src/components/naisu/tool-call.tsx",
  "tool-call-chips": "src/components/naisu/tool-call.tsx",
  "thinking-indicator": "src/components/naisu/thinking-indicator.tsx",
  "thinking-steps": "src/components/naisu/thinking-indicator.tsx",
  "thinking-reasoning": "src/components/naisu/thinking-indicator.tsx",
  "streaming-text": "src/components/naisu/streaming-text.tsx",
  "permission-request": "src/components/naisu/permission-request.tsx",
  tasks: "src/components/naisu/task-rows.tsx",
  recommendation: "src/components/naisu/recommendation.tsx",
  "context-cards": "src/components/naisu/context-cards.tsx",
  "selection-actions": "src/components/naisu/selection-actions.tsx",
  toast: "src/components/naisu/toast.tsx",
  dialog: "src/components/naisu/system-dialog.tsx",
  "empty-state": "src/components/naisu/empty-state.tsx",
  "settings-panel": "src/components/naisu/settings-panel.tsx",
  status: "src/components/naisu/status.tsx",
  loading: "src/components/naisu/loading-state.tsx",
  "loading-dots": "src/components/naisu/loading-state.tsx",
  "loading-ring": "src/components/naisu/loading-state.tsx",
  "loading-bars": "src/components/naisu/loading-state.tsx",
  progress: "src/components/naisu/progress.tsx",
  "motion-button": "src/components/naisu/motion-button.tsx",
  "motion-tabs": "src/components/naisu/motion-tabs.tsx",
  "option-selector": "src/components/naisu/option-selector.tsx",
}
